import { inviteExistingPartner, updateNetworkConnection } from "@/app/actions/network-os";
import { Flash } from "@/components/workspace/flash";
import { EmptyState, PageHeader, StatusBadge } from "@/components/ui";
import { requireVerifiedRole } from "@/lib/auth";
import { db } from "@/lib/db";
import { getCompanyOrganization } from "@/lib/network";

export default async function CompanyNetworkPage({ searchParams }: { searchParams: Promise<{ notice?: string; error?: string }> }) {
  const [user, flash] = await Promise.all([requireVerifiedRole("COMPANY"), searchParams]); const organization = await getCompanyOrganization(user);
  const connections = await db.companyPartnerConnection.findMany({ where: { organizationId: organization.id }, include: { partner: { include: { capacityPulses: { orderBy: { confirmedAt: "desc" }, take: 1 }, verificationCases: { orderBy: { createdAt: "desc" }, take: 1 } } } }, orderBy: { createdAt: "desc" } });
  return <><PageHeader title="Private partner network" sub="Invite known partners, control access and see verification plus live capacity before routing." /><Flash {...flash} /><div className="card mb-6 p-5"><form action={inviteExistingPartner} className="flex flex-col gap-3 sm:flex-row"><input className="input" type="email" name="email" placeholder="Partner account email" required /><button className="btn btn-gold shrink-0">Invite existing partner</button></form><p className="mt-2 text-[11px] text-slate-400">Only an existing, email-verified partner account can be invited.</p></div>{connections.length ? <div className="space-y-3">{connections.map(({ id, status, partner }) => { const pulse = partner.capacityPulses[0]; const verification = partner.verificationCases[0]; return <div className="card p-5" key={id}><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{partner.displayName}</h2><StatusBadge status={status} /><StatusBadge status={verification?.status ?? "NOT_VERIFIED"} /><span className="ml-auto text-xs text-slate-500">{pulse ? `${pulse.status} · ${pulse.availableBand}` : "No live capacity"}</span></div><div className="mt-4 flex gap-2">{status === "ACTIVE" ? <form action={updateNetworkConnection}><input type="hidden" name="connectionId" value={id} /><input type="hidden" name="operation" value="PAUSED" /><button className="btn btn-ghost btn-sm">Pause</button></form> : status === "PAUSED" ? <form action={updateNetworkConnection}><input type="hidden" name="connectionId" value={id} /><input type="hidden" name="operation" value="ACTIVE" /><button className="btn btn-gold btn-sm">Activate</button></form> : null}</div></div>; })}</div> : <EmptyState title="No partners connected" body="Invite partners you already trust. They decide whether to join your private network." />}</>;
}
