import { respondToOffer } from "@/app/actions/network-os";
import { Flash } from "@/components/workspace/flash";
import { EmptyState, Field, KV, PageHeader, StatusBadge } from "@/components/ui";
import { requireVerifiedRole } from "@/lib/auth";
import { db } from "@/lib/db";
import { fmtDateTime, requestTypeLabel } from "@/lib/format";

export default async function PartnerOffersPage({ searchParams }: { searchParams: Promise<{ notice?: string; error?: string }> }) {
  const [user, flash] = await Promise.all([requireVerifiedRole("PARTNER"), searchParams]); const offers = user.partner ? await db.matchOffer.findMany({ where: { partnerId: user.partner.id }, include: { request: true, organization: true }, orderBy: { createdAt: "desc" } }) : [];
  return <><PageHeader title="Private match offers" sub="Time-boxed, requirement-specific offers. Accepting confirms interest; it never executes a transaction." /><Flash {...flash} /><div className="space-y-4">{offers.length ? offers.map((offer) => { const expired = offer.expiresAt <= new Date(); return <div key={offer.id} className="card p-5"><div className="flex flex-wrap items-center gap-3"><span className="font-mono text-xs text-gold-700">{offer.reference}</span><StatusBadge status={expired && offer.status === "PENDING" ? "EXPIRED" : offer.status} /><span className="text-xs text-slate-400">Fit {offer.fitScore}/100</span><span className="ml-auto text-xs text-slate-400">expires {fmtDateTime(offer.expiresAt)}</span></div><h2 className="mt-3 text-base font-semibold">{requestTypeLabel(offer.request.requestType)}</h2><p className="mt-1 text-xs text-slate-500">From {offer.organization.name}</p><dl className="mt-4 grid grid-cols-2 gap-4 md:grid-cols-4"><KV label="Daily volume">{offer.request.dailyVolumeBand}</KV><KV label="Speed">{offer.request.requiredSpeed}</KV><KV label="Jurisdiction">{offer.request.jurisdiction}</KV><KV label="Signals">{offer.reasonCodes.map((reason) => reason.replaceAll("_", " ")).join(", ")}</KV></dl>{offer.status === "PENDING" && !expired ? <form action={respondToOffer} className="mt-5 grid gap-3 rounded-xl border border-gold-500/20 bg-gold-500/[0.04] p-4 sm:grid-cols-2"><input type="hidden" name="offerId" value={offer.id} /><Field label="Capacity you can commit"><input className="input" name="capacityBand" placeholder="₹1–2 crore today" /></Field><Field label="Terms note"><input className="input" name="termsSummary" placeholder="Conditions or timing" /></Field><div className="flex gap-2 sm:col-span-2"><button className="btn btn-gold btn-sm" name="decision" value="accept">Confirm interest</button><button className="btn btn-ghost btn-sm" name="decision" value="decline">Decline</button></div></form> : null}</div>; }) : <div className="card p-6"><EmptyState title="No offers yet" body="Keep verification approved and publish a fresh capacity pulse to become eligible." /></div>}</div></>;
}
