import { createIncident, resolveIncident } from "@/app/actions/network-os";
import { Flash } from "@/components/workspace/flash";
import { EmptyState, PageHeader, StatusBadge } from "@/components/ui";
import { db } from "@/lib/db";
import { fmtDateTime } from "@/lib/format";

export default async function AdminIncidentsPage({ searchParams }: { searchParams: Promise<{ notice?: string; error?: string }> }) {
  const [flash, incidents, partners] = await Promise.all([searchParams, db.incident.findMany({ include: { partner: true }, orderBy: { createdAt: "desc" }, take: 200 }), db.partnerProfile.findMany({ select: { id: true, displayName: true }, orderBy: { displayName: "asc" } })]);
  return <><PageHeader title="Incident register" sub="Operational, compliance and settlement signals that immediately affect private routing scores." /><Flash {...flash} /><div className="card mb-6 p-5"><form action={createIncident} className="grid gap-3 sm:grid-cols-2"><select className="input" name="partnerId" defaultValue=""><option value="">No specific partner</option>{partners.map((partner) => <option value={partner.id} key={partner.id}>{partner.displayName}</option>)}</select><select className="input" name="severity" defaultValue="MEDIUM"><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select><input className="input" name="category" placeholder="Category" /><input className="input" name="summary" placeholder="Incident summary" required /><textarea className="input sm:col-span-2" name="details" placeholder="Restricted operational details" /><button className="btn btn-gold sm:col-span-2">Open incident</button></form></div>{incidents.length ? <div className="space-y-3">{incidents.map((incident) => <div className="card p-5" key={incident.id}><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-xs text-gold-700">{incident.reference}</span><StatusBadge status={incident.severity} /><StatusBadge status={incident.status} /><span className="ml-auto text-[11px] text-slate-400">{fmtDateTime(incident.createdAt)}</span></div><h2 className="mt-3 text-sm font-semibold">{incident.summary}</h2><p className="mt-1 text-xs text-slate-500">{incident.partner?.displayName ?? "Network-wide"} · {incident.category}</p>{incident.details ? <p className="mt-3 text-xs leading-relaxed text-slate-600">{incident.details}</p> : null}{incident.status !== "RESOLVED" ? <form action={resolveIncident} className="mt-4"><input type="hidden" name="incidentId" value={incident.id} /><button className="btn btn-ghost btn-sm">Resolve</button></form> : null}</div>)}</div> : <EmptyState title="No incidents" body="Keep the register clean, factual and evidence-backed." />}</>;
}
