import { publishCapacityPulse } from "@/app/actions/network-os";
import { Flash } from "@/components/workspace/flash";
import { PageHeader, StatusBadge } from "@/components/ui";
import { requireVerifiedRole } from "@/lib/auth";
import { db } from "@/lib/db";
import { directionLabel, fmtDateTime } from "@/lib/format";

export default async function PartnerCapacityPage({ searchParams }: { searchParams: Promise<{ notice?: string; error?: string }> }) {
  const [user, flash] = await Promise.all([requireVerifiedRole("PARTNER"), searchParams]); const pulses = user.partner ? await db.capacityPulse.findMany({ where: { partnerId: user.partner.id }, orderBy: { confirmedAt: "desc" }, take: 10 }) : [];
  return <><PageHeader title="Live capacity pulse" sub="Publish short-lived availability. Expired pulses are never eligible for routing." /><Flash {...flash} /><div className="card mb-6 p-5"><form action={publishCapacityPulse} className="grid gap-3 sm:grid-cols-2"><select className="input" name="status" defaultValue="AVAILABLE"><option>AVAILABLE</option><option>LIMITED</option><option>PAUSED</option><option>OFFLINE</option></select><select className="input" name="direction"><option value="INR_TO_USDT">INR → USDT</option><option value="USDT_TO_INR">USDT → INR</option><option value="INR_PAYOUTS">INR payouts</option></select><input className="input" name="availableBand" placeholder="Available band, e.g. ₹1–2 crore" required /><input className="input" name="hours" type="number" min="1" max="24" defaultValue="8" /><input className="input" name="minTicket" placeholder="Minimum ticket" /><input className="input" name="maxTicket" placeholder="Maximum ticket" /><input className="input" name="banks" placeholder="Bank (repeat in profile for multiple)" /><input className="input" name="methods" placeholder="Rail/method" /><button className="btn btn-gold sm:col-span-2">Publish capacity</button></form></div><div className="space-y-3">{pulses.map((pulse) => <div className="card flex flex-wrap items-center gap-3 p-4" key={pulse.id}><StatusBadge status={pulse.availableUntil <= new Date() ? "EXPIRED" : pulse.status} /><span className="text-sm font-medium">{directionLabel(pulse.direction)}</span><span className="text-xs text-slate-500">{pulse.availableBand}</span><span className="ml-auto text-[11px] text-slate-400">until {fmtDateTime(pulse.availableUntil)}</span></div>)}</div></>;
}
